### ISSUE TITLE
No 'Access-Control-Allow-Origin' header

### ISSUE THREAD

**Issue by HigherPixel** [ckatzorke/howlongtobeat#12]
Hello, I have just started using this package and I find it to be a great resource. I'm currently having a problem with one issue. When sending a request via the HowLongToBeatService, I get an error as response saying

"Access to fetch at 'https://howlongtobeat.com/search_results.php?page=1' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled."

I'm currently using a workaround with testing in chrome but when out of testing, this issue will still persist. What course of action should I take to remedy this error.

Thanks

**Comment by HigherPixel** [comment]
I found another way around this issue by changing the HowLongToBeatService base url in the howlongtobeat.js file in the node_module to HowLongToBeatService.BASE_URL = 'https://cors-anywhere.herokuapp.com/https://howlongtobeat.com/'; and then run

 npx patch-package howlongtobeat

This fixes the issue locally

**Comment by kushthakker** [comment]
> I found another way around this issue by changing the HowLongToBeatService base url in the howlongtobeat.js file in the node_module to HowLongToBeatService.BASE_URL = 'https://cors-anywhere.herokuapp.com/https://howlongtobeat.com/'; and then run
> 
> npx patch-package howlongtobeat
> 
> This fixes the issue locally
> 
> //Edit New Update
> After more looking, I think this is an issue on my end and not this package so I closed the issue

Hey mate, I am having the same issue so can you please imply on how your error got fixed?

**Comment by ckatzorke** [comment]
That is really weird. My tests (also integration tests) are still running, and I also have a serverless function running the latest npm module - without any issues...

**Comment by GamerKingFaiz** [comment]
I'm having the same issue as the OP. I tried following the workaround they posted and I'm not sure if I'm doing it right because I still see the original URL in the console logs.

![image](https://user-images.githubusercontent.com/9065136/147402067-c5ed12e2-9ed2-4d64-9fcc-f366dfd0ba9c.png)

I assume we're both trying to implement this in React because we're on http://localhost:3000. Is this a React related issue?

Additionally I also see this in the console logs, but I assume it's related to the original issue of not getting a response because of the CORS issue.

![image](https://user-images.githubusercontent.com/9065136/147402124-7a4a21ca-4301-4969-b5dc-c03bcddab747.png)

**Comment by GamerKingFaiz** [comment]
I found that this issue was only occurring in my local React dev environment. I tested deploying my app to [GitHub Pages](https://create-react-app.dev/docs/deployment/#github-pages) and it worked fine there.

For local development I'm using this browser extension: [Allow CORS: Access-Control-Allow-Origin](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en)

**Comment by GamerKingFaiz** [comment]
Okay, (hopefully) final update. I was able to get my React app to finally pick up the changes I made to the `howlongtobeat` repo by forking this repo and then using
```
npm install git+<my forked repo>
```

Kudos to [this StackOverflow answer](https://stackoverflow.com/a/63998617/14000052).
